among_us_finder/apps/rooms/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from among_us_finder.apps.rooms import views

app_name = 'rooms'

urlpatterns = [
    path('create_room', login_required(views.CreateRoomFormView.as_view()), name='create_room_form'),
    path('room_created', views.RoomCreatedView.as_view(), name='room_created'),
    path('room_list', views.RoomList.as_view(), name='room_list'),
    path('<int:pk>', views.JoinRoom.as_view(), name='room_detail'),
    path('room_conversation/<int:pk>', login_required(views.RoomConversation.as_view()), name='room_conversation'),
    path('leave_room/<int:pk>', login_required(views.LeaveRoomView.as_view()), name='leave_room'),
    path('user_rooms', login_required(views.UserRooms.as_view()), name='user_room'),
    path('participants_list/<int:pk>', login_required(views.ParticipantList.as_view()), name='participants_list'),
    path('delete_participant/<int:room_pk>/<int:user_pk>/', login_required(views.DeleteParticipant.as_view()),
         name='participant_delete'),
    path('join_error/<str:error_code>/', views.JoinRoomError.as_view(), name='join_room_error'),
    path('report_user/<int:user_pk>/<int:room_pk>/', login_required(views.ReportUserFormView.as_view()),
         name='report_user'),
    path('report_user/<int:user_pk>/<int:room_pk>/user_reported/', views.ReportSuccess.as_view(), name='user_reported'),
]

among_us_finder/apps/users/urls.py
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [
	path('signup', views.SignupView.as_view(), name='signup_form'),
	path('registered', views.RegistrationCompleted.as_view(), name='registration_completed'),
	path('login', views.MyLoginView.as_view(), name='login_form'),
	path('logout', views.MyLogoutView.as_view(), name='logout_form'),
]

among_us_finder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import generic as views_generic

urlpatterns = [
    path('', views_generic.TemplateView.as_view(template_name='homepage.html'), name='homepage'),
    path('admin/', admin.site.urls),
    path('users/', include('among_us_finder.apps.users.urls')),
    path('rooms/', include('among_us_finder.apps.rooms.urls')),
]

among_us_finder/apps/rooms/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from among_us_finder.apps.rooms.constants import MapChoices, LevelChoices


class Room(models.Model):
    name = models.CharField(max_length=20, blank=True)
    game_start = models.DateTimeField()
    level = models.PositiveSmallIntegerField(choices=LevelChoices.Choices)
    game_map = models.PositiveSmallIntegerField(choices=MapChoices.Choices, null=True, blank=True)
    players_number = models.PositiveSmallIntegerField(validators=[MinValueValidator(4), MaxValueValidator(15)])
    searched_players_number = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(14)])
    comment = models.TextField(blank=True)
    participants = models.ManyToManyField('users.User')
    host = models.ForeignKey('users.User', blank=False, null=True, on_delete=models.SET_NULL, related_name='host')


class Message(models.Model):
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    comment = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')

among_us_finder/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from among_us_finder.apps.rooms.constants import LevelChoices


class User(AbstractUser):
    level_of_advancement = models.PositiveSmallIntegerField(choices=LevelChoices.Choices)

among_us_finder/apps/rooms/forms.py
from django.forms import ModelForm
from django import forms
from django.core.exceptions import PermissionDenied

from among_us_finder.apps.rooms.models import Room, Message


class CreateRoomForm(ModelForm):

    class Meta:
        model = Room
        fields = ["name", "game_start", "game_map", "level", "players_number", "searched_players_number", "comment"]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('host', None)
        super().__init__(*args, **kwargs)
        self.fields['level'].label = 'Level of advancement'
        self.fields['searched_players_number'].label = 'How many players are you looking for'
        self.fields['name'].label = 'Name of the room (optional)'
        self.fields['game_map'].label = 'Map (optional)'
        self.fields['comment'].label = 'Comment (optional)'
        self.fields['game_start'].label = 'Date and time'
        self.fields['game_map'].required = False

    def save(self, commit=True):
        if not self.user:
            raise PermissionDenied()
        else:
            self.instance.host = self.user
            instance = super().save(commit)
            instance.participants.add(self.user)
            return instance

    def full_clean(self):
        super(CreateRoomForm, self).full_clean()
        if self.is_valid():
            if self.cleaned_data.get('searched_players_number') >= self.cleaned_data.get('players_number'):
                self.add_error('searched_players_number', "It can't be bigger than players number")


class MessageForm(ModelForm):

    """Form to create comment in room"""

    class Meta:
        model = Message
        fields = ["comment", 'author', 'room']

    def __init__(self, *args, **kwargs):
        self.room = kwargs.pop('room')
        self.author = kwargs.pop('author')
        super().__init__(*args, **kwargs)
        self.fields['author'].required = False
        self.fields['room'].required = False

    def save(self, commit=True):
        self.instance.author = self.author
        self.instance.room = self.room
        instance = super().save(commit)
        instance.save()
        return instance


class ReportUser(forms.Form):

    """Form to report abuse"""

    reason = forms.CharField(widget=forms.Textarea)

among_us_finder/apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from among_us_finder.apps.users.models import User


class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'level_of_advancement')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username:'
        self.fields['username'].help_text = ''
        self.fields['email'].label = 'Email:'
        self.fields['password1'].label = 'Password:'
        self.fields['password1'].help_text = ''
        self.fields['password2'].label = 'Confirm the password:'
        self.fields['password2'].help_text = ''

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data['password1'])
        user.save()
        return user


class LoginForm(AuthenticationForm):

    class Meta:
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username:'
        self.fields['password'].label = 'Password:'

among_us_finder/apps/rooms/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.utils import timezone
from django.views.generic.edit import FormView, FormMixin
from django.views.generic import TemplateView, ListView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import mail_admins

import smtplib

from among_us_finder.apps.rooms.forms import CreateRoomForm, MessageForm, ReportUser
from among_us_finder.apps.rooms.models import Room
from among_us_finder.apps.rooms.constants import MapChoices, ROOM_ERROR_MAP
from among_us_finder.apps.users.models import User


class CreateRoomFormView(FormView):

    """View to create room"""
  
    template_name = 'rooms/create_room.html'
    form_class = CreateRoomForm
    success_url = 'room_created'

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs()
        if self.request.user.is_authenticated:
            kwargs['host'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class RoomCreatedView(TemplateView):
    template_name = 'rooms/created.html'


class RoomList(ListView):

    """View to list all active rooms"""

    model = Room
    template_name = 'rooms/room_list.html'
    ordering = ['game_start']

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['maps'] = MapChoices.Choices
        return ctx

    def get_queryset(self):
        qs = super().get_queryset().filter(game_start__gte=timezone.now())
        if self.request.GET.get('game_start_before'):
            time_before = self.request.GET.get('game_start_before')
            qs = qs.filter(game_start__lte=time_before)
        if self.request.GET.get('game_start_after'):
            time_after = self.request.GET.get('game_start_after')
            qs = qs.filter(game_start__lte=time_after)
        if self.request.GET.get('game_map'):
            game_map = self.request.GET.get('game_map')
            qs = qs.filter(map=game_map)
        return qs


class JoinRoom(DetailView):

    """View to join room.

    With validation if amount of paricipants is ok and if user didn't join this room earlier. In case of error redirects
    to JoinRoomError view"""

    model = Room
    template_name = 'rooms/room_detail.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            ctx['user'] = self.request.user
        return ctx

    def post(self, *args, **kwargs):
        room = self.get_object()
        if self.request.user in room.participants.all():
            return redirect('rooms:join_room_error', error_code='already_in_room')
        if room.participants.count() >= room.searched_players_number:
            return redirect('rooms:join_room_error', error_code='no_place')
        else:
            room.participants.add(self.request.user)
            return redirect('rooms:room_conversation', pk=self.kwargs.get('pk'))


class RoomDetail(DetailView):

    """View to join room and room conversation."""

    model = Room
    template_name = 'rooms/room_detail.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            ctx['user'] = self.request.user
        return ctx

    def post(self, *args, **kwargs):
        room = self.get_object()
        if self.request.user in room.participants.all():
            return redirect('rooms:join_room_error', error_code='already_in_room')
        if room.participants.count() >= room.searched_players_number:
            return redirect('rooms:join_room_error', error_code='no_place')
        else:
            room.participants.add(self.request.user)
            return redirect('rooms:room_conversation', pk=self.kwargs.get('pk'))


class JoinRoomError(TemplateView):

    """View with join errors"""

    template_name = 'rooms/no_place.html'

    def get_context_data(self, **kwargs):
        ctx = super(JoinRoomError, self).get_context_data(**kwargs)
        ctx['error_msg'] = ROOM_ERROR_MAP.get(self.kwargs.get('error_code'))
        return ctx


class RoomConversation(PermissionRequiredMixin, FormMixin, DetailView):

    """View to read and create message in room conversation.

    Validation if user joined room (have permission to read and write comments.
    """
    
    model = Room
    template_name = 'rooms/room_conversation.html'
    form_class = MessageForm
    http_method_names = ['get', 'post']

    def has_permission(self):
        room = self.get_object()
        return room.participants.filter(pk=self.request.user.pk).exists()

    def handle_no_permission(self):
        return redirect(reverse_lazy("rooms:room_list"))

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            ctx['user'] = self.request.user
            ctx['msgs'] = self.get_object().messages.all()
        return ctx

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['author'] = self.request.user
        kwargs['room'] = self.get_object()
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('rooms:room_conversation', kwargs={'pk': self.kwargs.get('pk')})


class ParticipantList(DetailView):

    """List of participants who joined room"""

    model = Room
    template_name = 'rooms/participantslist.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            ctx['user'] = self.request.user
            ctx['participants'] = self.get_object().participants.all()
            ctx['host'] = self.get_object().host
            ctx['is_host'] = self.get_object().host == self.request.user
        return ctx


class DeleteParticipant(TemplateView):

    """Host can delete participant from room"""

    model = Room
    template_name = 'rooms/delete_user.html'

    def post(self, *args, **kwargs):
        room = Room.objects.get(pk=kwargs.get('room_pk'))
        if self.request.user != room.host:
            return HttpResponse('Unauthorized', status=401)
        room.participants.remove(User.objects.get(pk=kwargs.get('user_pk')))
        return redirect('rooms:participants_list', pk=kwargs.get('room_pk'))


class LeaveRoomView(DetailView):


    """View to leave room"""

    model = Room
    template_name = 'rooms/leave_room.html'

    def post(self, *args, **kwargs):
        room = self.get_object()
        room.participants.remove(self.request.user)
        return redirect('rooms:room_list')


class UserRooms(ListView):

    """List of user's actual and old rooms (rooms she/he joined)"""

    model = Room
    template_name = 'rooms/user_view.html'
    context_object_name = 'rooms_types'

    def get_queryset(self):
        rooms = Room.objects.filter(participants=self.request.user).order_by("-game_start")
        qs = {'Actual': rooms.filter(game_start__gte=timezone.now()),
              'Old': rooms.filter(game_start__lt=timezone.now())}
        return qs


class ReportUserFormView(FormView):

    """View with form to report abuse"""

    template_name = 'rooms/report_user.html'
    form_class = ReportUser
    success_url = 'user_reported'

    def form_valid(self, form):
        reporting_user = self.request.user
        reported_user = get_object_or_404(User, pk=self.kwargs.get('user_pk'))
        room = get_object_or_404(Room, pk=self.kwargs.get('room_pk'))
        reason = form.cleaned_data['reason']
        subject = "Abuse report"
        body = {
            'username': reporting_user.username,
            'reported_username': reported_user.username,
            'room': str(room.id),
            'reason': reason,
        }
        try:
            message = "\n".join(body.values())
            mail_admins(subject, message)
            return super().form_valid(form)
        except smtplib.SMTPException:
            return HttpResponse('Invalid header found.')


class ReportSuccess(TemplateView):
    template_name = 'rooms/report_success.html'

among_us_finder/apps/users/views.py
from django.urls import reverse
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import logout

from among_us_finder.apps.users.forms import SignupForm, LoginForm


class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = 'registered'

    def form_valid(self, form):
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class RegistrationCompleted(TemplateView):
    template_name = 'users/registration_completed.html'


class MyLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = LoginForm

    def get_success_url(self):
        next_url = self.request.GET.get('next', None)
        if next_url:
            return "%s" % (next_url)
        return reverse('rooms:room_list')


class MyLogoutView(LogoutView):

    def logout_view(request):
        logout(request)

among_us_finder/templates/rooms/create_room.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        Create room:
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create!</button>
        </form>
    {% else %}
        <p>Log in:</p>
        <button><a href="{% url 'users:login_form' %}" >Log in</a></button>

        <p>Registration:</p>
        <button><a href="{% url 'users:signup_form' %}">Sign up</a></button>
    {% endif %}

{% endblock %}

among_us_finder/templates/rooms/created.html
{% extends 'base.html' %}

{% block content %}

    Room created!

    <br>
    <button><a href="{% url 'rooms:user_room' %}" type="submit">My rooms</a></button>
    <button><a href="{% url 'rooms:room_list' %}" type="submit">All rooms</a></button>

{% endblock %}

among_us_finder/templates/rooms/delete_user.html
{% extends 'base.html' %}

    {% block content %}

        Do you want to delete this user from room
        {% if room.name %}
            {{ room.name }}
        {% else %}
            {{ room.pk }}
        {% endif %}?
           <p> <form method="post" >{% csrf_token %}
                <button>Yes</button>
            </form>
            <p><a href="{% url 'rooms:participants_list' room_pk %}"><button>No</button></a></p>

    {% endblock %}

among_us_finder/templates/rooms/leave_room.html
{% extends 'base.html' %}

    {% block content %}

        You left the room.

        <p><a href="{% url 'rooms:room_list' %}" type="submit"><button>Go to rooms list</button></a></p>

    {% endblock %}

among_us_finder/templates/rooms/no_place.html
{% extends 'base.html' %}

{% block content %}

    {{ error_msg }}

{% endblock %}

among_us_finder/templates/rooms/participantslist.html
{% extends 'base.html' %}

    {% block content %}

        {% if room.name %}
            {{ room.name }}
        {% else %}
            {{ room.pk }}.
        {% endif %}
            {{ room.game_start }}
        <p>
        {% for user in participants %}
            <p>
                {{ user.username }}
                {% if is_host %}<button><a href="{% url 'rooms:participant_delete' room.pk user.pk %}">Delete from room</a></button>{% endif %}
                <button><a href="{% url 'rooms:report_user' user.pk room.pk%}">Report abuse</a></button>
            </p>
        {% endfor %}

        Host: {{ host }}

    {% endblock %}

among_us_finder/templates/rooms/report_success.html
{% extends 'base.html' %}

{% block content %}

    Abuse reported.

    <p><a href="{% url 'rooms:room_list' %}" type="submit"><button>Go to rooms list</button></a></p>

{% endblock %}

among_us_finder/templates/rooms/report_user.html
{% extends 'base.html' %}

    {% block content %}

            <p>
            <form method="post" >{% csrf_token %}
                {{ form }}
            <button>Send</button>
            </form>

    {% endblock %}

among_us_finder/templates/rooms/room_conversation.html
{% extends 'base.html' %}

    {% block content %}

        {% if user.is_authenticated %}

            {% if room.name %}
                {{ room.name }}
            {% else %}
                {{ room.pk }}.
            {% endif %}
                {{ room.game_start }}

           <p><a href="{% url 'rooms:participants_list' room.pk %}"><button>Participants list</button></a></p>

            {% for message in msgs %}
                <p> {{ message.published }}</p>
                <p>{{ message.author }}</p>
                <p>{{ message.comment }}</p>

            {% empty %}
                <li>No messages yet.</li>
            {% endfor %}

            <form method="post">{% csrf_token %}
                {{ form.comment }}
               <button type="submit">Send</button>
            </form>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            <form method="post" action="{% url 'rooms:leave_room' room.pk %}">{% csrf_token %}
                <button>Leave room</button>
            </form>

        {% else %}
            <p>Log in:</p>
            <button><a href="{% url 'users:login_form' %}" >Log in</a></button>

            <p>Registration:</p>
            <button><a href="{% url 'users:signup_form' %}">Sign up</a></button>
        {% endif %}

    {% endblock %}

among_us_finder/templates/rooms/room_detail.html
{% extends 'base.html' %}

    {% block content %}
        {% if room.name %}
            <p>{{room.name}}:</p>
        {% endif %}
        <p>{{ room.game_start }}</p>
        <p>Level of game advancement: {{ room.get_level_display }} </p>
        <p>Total players number: {{ room.players_number }} </p>
        <p>Looking for {{ room.searched_players_number }} players </p>
        <p>{{ room.comment }}</p>

        {% if user.is_authenticated %}
            <form method="post">{% csrf_token %}
             <button>Join!</button>
            </form>
        {% else %}
            <a href="{% url 'users:login_form' %}?next={% url 'rooms:room_detail' room.pk %}" type="submit"><button>Log in!</button></a>
        {% endif %}

    {% endblock %}

among_us_finder/templates/rooms/room_list.html
{% extends 'base.html' %}

    {% block content %}

    <div>
        Search:
        <form method="get">
            <label>Time from: </label><input type="datetime-local" name="start_game_before">

            <label>Time to: </label><input type="datetime-local" name="start_game_after">

            <label>Map: </label>

            <select name="game_map" id="maps">
                {% for value, name in maps %}
                    <option value="{{ value }}" {% if value|stringformat:"i" == request.GET.game_map %}selected{% endif %}>{{ name }}</option>
                {% endfor %}
            </select>
            <br><button type="submit" class="save">Search</button>
        </form>
        <br>
    </div>
        Rooms:
        {% for room in room_list %}
           <a href = "{% url 'rooms:room_detail' room.pk %}" >
               {% if room.name %}
                    <p>{{room.name}}:
               {% else %}
                    <p>{{ room.id }}:
               {% endif %}
               {{ room.game_start }}, {{ room.get_level_display }}, total players: {{ room.players_number }}, lack: {{ room.searched_players_number }}
                    </p>
           </a>
        {% empty %}
            <li>No rooms yet.</li>
        {% endfor %}

    <br>
    <button><a href="{% url 'rooms:create_room_form' %}" type="submit">Create room</a></button>
    <button><a href="{% url 'rooms:user_room' %}" type="submit">My rooms</a></button>
    {% endblock %}

among_us_finder/templates/rooms/searcher.html
<!-- do pierwszej wersji wyszukiwarki -->

{% extends 'base.html' %}

{% block content %}

    Find room:
        <form method="get">
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Search</button>
        </form>

{% endblock %}

among_us_finder/templates/rooms/user_view.html
{% extends 'base.html' %}

    {% block content %}

        {% for name, rooms in rooms_types.items %}
            {{ name }}:
            {% for room in rooms %}
               <a href = "{% url 'rooms:room_conversation' room.pk %}">
                   {% if room.name %}
                        <p>{{room.name}}:
                   {% else %}
                        <p>{{ room.id }}:
                   {% endif %}
                   {{ room.game_start }}, {{ room.get_level_display }}, total players: {{ room.players_number }}, lack: {{ room.searched_players_number }}
                        </p>
               </a>
            {% empty %}
                <li>No rooms yet.</li>
            {% endfor %}
        {% endfor %}

        <a href="{% url 'rooms:create_room_form' %}" type="submit"><button>Create room</button></a>

    {% endblock %}